version: '2'
services:
 prometheus:
   image: prom/prometheus:latest
   volumes:
     - /opt/docker/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - /opt/docker/data/prometheus/prometheus_db:/var/lib/prometheus
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
   networks:
     bridge:
       ipv4_address: 172.17.0.10
 node-exporter:
  image: prom/node-exporter
  networks:
      bridge:
        ipv4_address: 172.17.0.11
 cadvisor:
  image: google/cadvisor:latest
  networks:
      bridge:
        ipv4_address: 172.17.0.12
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

 grafana:
  image: grafana/grafana
  user: "1000"
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=passW0rd
  volumes:
   - /opt/docker/data/grafana/grafana_db:/var/lib/grafana
  depends_on:
   - prometheus
  networks:
      bridge:
        ipv4_address: 172.17.0.13

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
