
global:
 scrape_interval: 5s
 external_labels:
   monitor: 'guidanz-monitor'
scrape_configs:
 - job_name: 'prometheus'
   static_configs:
     - targets: ['172.25.0.10:9090']
 - job_name: 'node-exporter'
   static_configs:
     - targets: ['172.25.0.11:9100']
 - job_name: 'cAdvisor'
   static_configs:
     - targets: ['172.25.0.12:8080']
